#!/bin/bash

echo "running pre-commit hook"
if grep -E "EMAIL_PASS=.+" docker/container.env; then
  echo "Error: EMAIL_PASS found in docker/container.env. Remove sensitive information before committing."
  exit 1
fi

