#!/bin/bash

# Define a variable with the patterns to exclude
EXCLUDE_PATTERNS="EMAIL_PASS=.+|PAYPAL_CLIENT_SECRET=.+"

# Check if any of the patterns are found in docker/container.env
if grep -E "$EXCLUDE_PATTERNS" docker/container.env; then
  echo "Error: Sensitive information found in docker/container.env. Remove before committing."
  exit 1
fi

# Run pnpm format and check for errors
if ! pnpm format; then
  echo "Error: Code formatting failed. Please fix the issues before committing."
  exit 1
fi

# Run pnpm lint and check for errors
# if ! pnpm lint; then
#   echo "Error: Linting failed. Please fix the issues before committing."
#   exit 1
# fi

echo "Pre-commit checks passed successfully."
